FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
	libpq-dev gcc

ENV PYTHONPATH /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["gunicorn", "--bind", ":8000", "--workers", "1", "app.wsgi:application"]



